version: '2'
services:
    web:
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile-install
            args:
                github_oauth: ###github_auth####
        container_name: ###projectname###_web_local
        restart: 'no'
        links:
            - nginx
        volumes:
            - './sources:/var/www/html/'
            - ./config/oro_php.ini:/usr/local/etc/php/php.ini:ro
            - ./config/apache-vhost.conf:/etc/apache2/sites-enabled/000-default.conf
            - $SSH_AUTH_SOCK:/ssh-agent
            - /home/###hostuser###/.ssh:/home/###hostuser###/.ssh
        environment:
            SSH_AUTH_SOCK: /ssh-agent
            APP_ENV: 'dev'
            APPLICATION_URL: http://localhost:8000
            ORGANIZATION_NAME: ###projectname###
            VIRTUAL_HOST: ###projectname###.dmk
            VIRTUAL_PORT: 8000
            HOST_USER: '###hostuser###'
            HOST_USER_ID: '###hostuserid###'
            HOST_GROUP: '###hostgroup###'
            HOST_GROUP_ID: '###hostgroupid###'
            USER_NAME: admin
            USER_EMAIL: admin@local.de
            USER_FIRSTNAME: John
            USER_LASTNAME: Doe
            USER_PASSWORD: admin
            SAMPLE_DATA: n
    oro-db:
        restart: 'no'
    redis:
        image: redis
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
