FROM php:5.6-apache

ARG user_id
ARG group_id

MAINTAINER Mario Seidel <info@maniox.de>

#install requirements
RUN apt-get update && \
    apt-get install -y git \
    libxml2-dev libfreetype6-dev \
    libjpeg62-turbo-dev \
    libmcrypt-dev \
    libpng12-dev \
    libicu-dev \
    zlib1g-dev

#enable PHP Extensions
RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ && \
    docker-php-ext-install -j$(nproc) mysqli soap gd zip intl mbstring mcrypt pdo pdo_mysql

#copy oro php configuration
COPY config/oro_php.ini /usr/local/etc/php/conf.d/oro_php.ini


#install composer
RUN cd /usr/local/bin/ && \
        php -r "readfile('https://getcomposer.org/installer');" > composer-setup.php && \
        php -r "if (hash('SHA384', file_get_contents('composer-setup.php')) === 'fd26ce67e3b237fffd5e5544b45b0d92c41a4afe3e3f778e942e43ce6be197b9cdc7c251dcde6e2a52297ea269370680') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); }" && \
        php composer-setup.php && \
        php -r "unlink('composer-setup.php');" && \
        chmod +x /usr/local/bin/composer.phar

CMD ["composer.phar", "diagnose"]
        

