version: '2'
services:
    web:
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile-install
            args:
                github_oauth: [github_oauth]
        container_name: [projectname]_web_local
        restart: 'no'
        volumes:
            - './sources:/var/www/html/'
        environment:
            APP_ENV: 'dev'
            APPLICATION_URL: http://localhost:8000
            ORGANIZATION_NAME: [projectname]
            USER_NAME: admin
            USER_EMAIL: admin@local.de
            USER_FIRSTNAME: John
            USER_LASTNAME: Doe
            USER_PASSWORD: admin
            SAMPLE_DATA: n
    oro-db:
        restart: 'no'
