version: '2'
services:
    web:
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile-prod
        container_name: [projectname]_web_prod
        volumes:
            - /var/www/html/app/cache
            - /var/www/html/app/logs
            - /var/www/html/web
        environment:
            APP_ENV: 'prod'
            
