parameters:
    database_driver:   pdo_mysql
    database_host:     oro_db
    database_port:     3306
    database_name:     oro_crm
    database_user:     oro_usr
    database_password: oro_pwd

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_port:       ~
    mailer_encryption: ~
    mailer_user:       ~
    mailer_password:   ~

    # WebSocket server config
    websocket_bind_address:  "0.0.0.0"  # The host IP the socket server will bind to
    websocket_bind_port:     8080       # The port the socket server will listen on
    websocket_frontend_host: "*"        # Websocket host the browser will connect to
    websocket_frontend_port: 8080       # Websocket port the browser will connect to
    websocket_backend_host:  "*"        # Websocket host the application server will connect to
    websocket_backend_port:  8080       # Websocket port the application server will connect to

    session_handler:   session.handler.native_file

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
    installed:         ~
    assets_version:    ~
    assets_version_strategy: time_hash # A strategy should be used to generate the global assets version, can be:
                                       # null        - the assets version stays unchanged
                                       # time_hash   - a hash of the current time
                                       # incremental - the next assets version is the previous version is incremented by one (e.g. 'ver1' -> 'ver2' or '1' -> '2')
